"""
Audit Report Generator
=======================
Generates HTML audit reports summarizing per-class robustness
profiles and fairness metrics for a given model.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List

sys_path_set = False

logger = logging.getLogger("gf_score.auditing_tool.report")


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GF-Score Robustness Audit Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background: #f5f5f5; color: #333; }}
        .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        .metric-card {{ background: #ecf0f1; padding: 15px 20px; border-radius: 6px; margin: 10px 0; display: inline-block; min-width: 180px; text-align: center; }}
        .metric-card .value {{ font-size: 28px; font-weight: bold; color: #2c3e50; }}
        .metric-card .label {{ font-size: 12px; color: #7f8c8d; text-transform: uppercase; }}
        .pass {{ color: #27ae60; }} .warn {{ color: #f39c12; }} .fail {{ color: #e74c3c; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th {{ background: #3498db; color: white; padding: 10px 15px; text-align: left; }}
        td {{ padding: 8px 15px; border-bottom: 1px solid #ddd; }}
        tr:nth-child(even) {{ background: #f9f9f9; }}
        .footer {{ margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }}
        .bar {{ height: 18px; background: #3498db; border-radius: 3px; display: inline-block; }}
    </style>
</head>
<body>
<div class="container">
    <h1>🛡️ GF-Score Robustness Audit Report</h1>
    <p><strong>Model:</strong> {model_name}<br>
    <strong>Date:</strong> {timestamp}<br>
    <strong>Data Source:</strong> {data_source} | Samples: {total_samples}</p>

    <h2>Summary Metrics</h2>
    <div>
        <div class="metric-card">
            <div class="value">{aggregate_score:.4f}</div>
            <div class="label">GREAT Score (Ω̂)</div>
        </div>
        <div class="metric-card">
            <div class="value {rdi_class}">{rdi:.4f}</div>
            <div class="label">RDI (Disparity)</div>
        </div>
        <div class="metric-card">
            <div class="value">{nrgc:.4f}</div>
            <div class="label">NRGC (Gini)</div>
        </div>
        <div class="metric-card">
            <div class="value {wcr_class}">{wcr:.4f}</div>
            <div class="label">WCR (Worst-Case)</div>
        </div>
        <div class="metric-card">
            <div class="value">{fp_great:.4f}</div>
            <div class="label">FP-GREAT (λ={fp_lambda})</div>
        </div>
    </div>

    <h2>Per-Class Robustness Profile</h2>
    <table>
        <tr><th>Class</th><th>GREAT Score</th><th>Clean Accuracy</th><th>Visual</th></tr>
        {per_class_rows}
    </table>

    <h2>Vulnerability Ranking</h2>
    <p>Classes ordered from <span class="fail">most vulnerable</span> to <span class="pass">most robust</span>:</p>
    <table>
        <tr><th>Rank</th><th>Class</th><th>Score</th><th>Status</th></tr>
        {vulnerability_rows}
    </table>

    <h2>Assessment</h2>
    <p>{assessment}</p>

    <div class="footer">
        Generated by GF-Score Auditing Tool v0.1.0 | 
        Based on GREAT Score (Li, Chen & Ho, NeurIPS 2024) extended with fairness metrics
    </div>
</div>
</body>
</html>"""


def generate_report(
    model_name: str,
    model_result: dict,
    data_source: str = "CIFAR-10 test",
    total_samples: int = 10000,
    output_dir: Path = None,
) -> str:
    """
    Generate an HTML audit report for a single model.

    Args:
        model_name: Display name of the model.
        model_result: Result dict from run_evaluation for this model.
        data_source: Description of data source.
        total_samples: Total number of evaluation samples.
        output_dir: Directory to save the report.

    Returns:
        Path to the generated report file.
    """
    if output_dir is None:
        import sys
        sys.path.insert(0, str(Path(__file__).parent.parent.parent))
        from gf_score.config import RESULTS_DIR
        output_dir = RESULTS_DIR / "reports"

    output_dir.mkdir(parents=True, exist_ok=True)

    # Build per-class rows
    per_class_scores = model_result.get("per_class_scores", {})
    per_class_accuracy = model_result.get("per_class_accuracy", {})
    max_score = max(per_class_scores.values()) if per_class_scores else 1.0

    per_class_rows = ""
    for cls_name in sorted(per_class_scores.keys()):
        score = per_class_scores[cls_name]
        acc = per_class_accuracy.get(cls_name, 0)
        bar_width = int((score / max(max_score, 0.001)) * 200)
        per_class_rows += (
            f"<tr><td>{cls_name}</td>"
            f"<td>{score:.4f}</td>"
            f"<td>{acc:.1%}</td>"
            f'<td><div class="bar" style="width:{bar_width}px"></div></td>'
            f"</tr>\n"
        )

    # Build vulnerability ranking
    vuln = model_result.get("vulnerability_ranking", [])
    vulnerability_rows = ""
    for rank, (cls_name, score) in enumerate(vuln, 1):
        if rank <= 3:
            status = '<span class="fail">⚠ Vulnerable</span>'
        elif rank >= len(vuln) - 2:
            status = '<span class="pass">✓ Robust</span>'
        else:
            status = '<span class="warn">— Average</span>'
        vulnerability_rows += (
            f"<tr><td>{rank}</td>"
            f"<td>{cls_name}</td>"
            f"<td>{score:.4f}</td>"
            f"<td>{status}</td></tr>\n"
        )

    # Assessment text
    rdi = model_result.get("rdi", 0)
    wcr = model_result.get("wcr", 0)
    wcr_class = model_result.get("wcr_class", "unknown")

    assessment_parts = []
    if rdi < 0.1:
        assessment_parts.append("This model exhibits <strong>low robustness disparity</strong> (RDI < 0.1), indicating relatively uniform robustness across classes.")
    elif rdi < 0.3:
        assessment_parts.append("This model exhibits <strong>moderate robustness disparity</strong> (0.1 ≤ RDI < 0.3), with some classes more vulnerable than others.")
    else:
        assessment_parts.append(f"This model exhibits <strong>high robustness disparity</strong> (RDI ≥ 0.3). The class <em>{wcr_class}</em> is significantly more vulnerable than others.")

    if wcr < 0.05:
        assessment_parts.append(f"<strong class='fail'>Critical:</strong> The worst-case class ({wcr_class}) has near-zero robustness (WCR = {wcr:.4f}), making it highly susceptible to adversarial attacks.")
    elif wcr < 0.2:
        assessment_parts.append(f"The worst-case class ({wcr_class}) has limited robustness (WCR = {wcr:.4f}).")

    assessment = " ".join(assessment_parts)

    # Determine CSS classes for color coding
    rdi_class = "pass" if rdi < 0.1 else ("warn" if rdi < 0.3 else "fail")
    wcr_css = "pass" if wcr > 0.2 else ("warn" if wcr > 0.05 else "fail")

    html = HTML_TEMPLATE.format(
        model_name=model_name,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        data_source=data_source,
        total_samples=total_samples,
        aggregate_score=model_result.get("aggregate_great_score", 0),
        rdi=rdi,
        rdi_class=rdi_class,
        nrgc=model_result.get("nrgc", 0),
        wcr=wcr,
        wcr_class=wcr_css,
        fp_great=model_result.get("fp_great", 0),
        fp_lambda=model_result.get("fp_lambda", 0.5),
        per_class_rows=per_class_rows,
        vulnerability_rows=vulnerability_rows,
        assessment=assessment,
    )

    safe_name = model_name.replace(" ", "_").replace("/", "_")
    report_path = output_dir / f"audit_report_{safe_name}.html"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html)

    logger.info(f"Generated audit report: {report_path}")
    return str(report_path)


def generate_all_reports(results: dict, output_dir: Path = None) -> List[str]:
    """Generate audit reports for all evaluated models."""
    model_results = results["model_results"]
    metadata = results.get("metadata", {})

    # Resolve short names from dataset config
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from gf_score.config import get_dataset_config
    dataset = metadata.get("dataset", "cifar10")
    ds_cfg = get_dataset_config(dataset)
    short_names = ds_cfg["short_names"]

    ds_label = "ImageNet" if dataset == "imagenet" else "CIFAR-10"

    paths = []
    for model_name, r in model_results.items():
        display_name = short_names.get(model_name, model_name)
        path = generate_report(
            model_name=display_name,
            model_result=r,
            data_source=metadata.get("data_source", f"{ds_label} test"),
            total_samples=metadata.get("total_samples", 0),
            output_dir=output_dir,
        )
        paths.append(path)

    print(f"\n✓ Generated {len(paths)} audit reports")
    return paths
